version: "3"
services:
  # This servie is responsible for running the web because
  # in Dockerfile.dev the default command is npm run start
  # When we try to run the test or add new test, it doesn't
  # get added automatically.
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: . # working directory same as docker-compose.yml
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    stdin_open: true # To handle react-dashboard_web_1 exited with code 0 Error.
    volumes:
      - /app/node_modules
      - .:/app
    restart: on-failure
  tests: # 2nd container responsible for running tests
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]

